# Generated by Django 6.0.7 on 2026-07-21 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Almoxarifado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('central', models.BooleanField(default=False, help_text='Estoque físico central (CSC) — único no sistema')),
                ('ativo', models.BooleanField(default=True)),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='almoxarifados', to='cadastros.filial')),
            ],
            options={
                'verbose_name': 'almoxarifado',
                'verbose_name_plural': 'almoxarifados',
                'ordering': ['filial', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='SaldoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('custo_medio', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estoque_minimo', models.DecimalField(blank=True, decimal_places=3, help_text='Definido apenas no almoxarifado central', max_digits=12, null=True)),
                ('ponto_reposicao', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('almoxarifado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saldos', to='estoque.almoxarifado')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saldos', to='cadastros.produto')),
            ],
            options={
                'verbose_name': 'saldo de estoque',
                'verbose_name_plural': 'saldos de estoque',
            },
        ),
        migrations.AddConstraint(
            model_name='almoxarifado',
            constraint=models.UniqueConstraint(fields=('filial', 'nome'), name='almoxarifado_unico_por_filial'),
        ),
        migrations.AddConstraint(
            model_name='almoxarifado',
            constraint=models.UniqueConstraint(condition=models.Q(('central', True)), fields=('central',), name='apenas_um_almoxarifado_central'),
        ),
        migrations.AddConstraint(
            model_name='saldoestoque',
            constraint=models.UniqueConstraint(fields=('produto', 'almoxarifado'), name='saldo_unico_por_produto_almoxarifado'),
        ),
        migrations.AddConstraint(
            model_name='saldoestoque',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade__gte', 0)), name='saldo_nunca_negativo'),
        ),
    ]
