# Generated by Django 6.0.7 on 2026-09-29 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
        ('pedidos', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DebitoAlmoxarifado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('credor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debitos_a_receber', to='tenancy.almoxarifado')),
                ('devedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debitos_devidos', to='tenancy.almoxarifado')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cadastros.produto')),
            ],
            options={
                'verbose_name': 'débito entre almoxarifados',
                'verbose_name_plural': 'débitos entre almoxarifados',
                'constraints': [models.UniqueConstraint(fields=('devedor', 'credor', 'produto'), name='debito_unico_por_par_produto'), models.CheckConstraint(condition=models.Q(('devedor', models.F('credor')), _negated=True), name='debito_devedor_diferente_credor')],
            },
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída/Consumo'), ('TRANSFERENCIA', 'Transferência'), ('DEVOLUCAO', 'Devolução'), ('AJUSTE', 'Ajuste')], max_length=20)),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=12)),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('arquivo_origem', models.CharField(blank=True, max_length=255)),
                ('observacao', models.CharField(blank=True, max_length=300)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_entrada', to='tenancy.almoxarifado')),
                ('origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_saida', to='tenancy.almoxarifado')),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='pedidos.pedido')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='cadastros.produto')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'movimentação',
                'verbose_name_plural': 'movimentações',
                'ordering': ['-criado_em'],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantidade__gt', 0)), name='movimentacao_quantidade_positiva'), models.CheckConstraint(condition=models.Q(models.Q(('destino__isnull', False), ('origem__isnull', True), ('tipo__in', ['ENTRADA', 'DEVOLUCAO'])), models.Q(('destino__isnull', True), ('origem__isnull', False), ('tipo', 'SAIDA')), models.Q(('destino__isnull', False), ('origem__isnull', False), ('tipo', 'TRANSFERENCIA')), ('tipo', 'AJUSTE'), _connector='OR'), name='movimentacao_origem_destino_coerentes'), models.CheckConstraint(condition=models.Q(('origem', models.F('destino')), ('tipo', 'TRANSFERENCIA'), _negated=True), name='transferencia_origem_diferente_destino')],
            },
        ),
        migrations.CreateModel(
            name='SaldoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('custo_medio', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estoque_minimo', models.DecimalField(blank=True, decimal_places=3, help_text='Definido apenas no almoxarifado central', max_digits=12, null=True)),
                ('ponto_reposicao', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('almoxarifado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saldos', to='tenancy.almoxarifado')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saldos', to='cadastros.produto')),
            ],
            options={
                'verbose_name': 'saldo de estoque',
                'verbose_name_plural': 'saldos de estoque',
                'constraints': [models.UniqueConstraint(fields=('produto', 'almoxarifado'), name='saldo_unico_por_produto_almoxarifado'), models.CheckConstraint(condition=models.Q(('quantidade__gte', 0)), name='saldo_nunca_negativo')],
            },
        ),
    ]
