# Generated by Django 6.0.7 on 2026-07-21 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_produto_codigo'),
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebitoAlmoxarifado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('credor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debitos_a_receber', to='estoque.almoxarifado')),
                ('devedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debitos_devidos', to='estoque.almoxarifado')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cadastros.produto')),
            ],
            options={
                'verbose_name': 'débito entre almoxarifados',
                'verbose_name_plural': 'débitos entre almoxarifados',
            },
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída/Consumo'), ('TRANSFERENCIA', 'Transferência'), ('DEVOLUCAO', 'Devolução'), ('AJUSTE', 'Ajuste')], max_length=20)),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=12)),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('arquivo_origem', models.CharField(blank=True, max_length=255)),
                ('observacao', models.CharField(blank=True, max_length=300)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_entrada', to='estoque.almoxarifado')),
                ('origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_saida', to='estoque.almoxarifado')),
            ],
            options={
                'verbose_name': 'movimentação',
                'verbose_name_plural': 'movimentações',
                'ordering': ['-criado_em'],
            },
        ),
    ]
