# Generated by Django 6.0.7 on 2026-07-21 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_produto_codigo'),
        ('estoque', '0002_debitoalmoxarifado_movimentacao'),
        ('pedidos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='pedidos.pedido'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='cadastros.produto'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='debitoalmoxarifado',
            constraint=models.UniqueConstraint(fields=('devedor', 'credor', 'produto'), name='debito_unico_por_par_produto'),
        ),
        migrations.AddConstraint(
            model_name='debitoalmoxarifado',
            constraint=models.CheckConstraint(condition=models.Q(('devedor', models.F('credor')), _negated=True), name='debito_devedor_diferente_credor'),
        ),
        migrations.AddConstraint(
            model_name='movimentacao',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade__gt', 0)), name='movimentacao_quantidade_positiva'),
        ),
        migrations.AddConstraint(
            model_name='movimentacao',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('destino__isnull', False), ('origem__isnull', True), ('tipo__in', ['ENTRADA', 'DEVOLUCAO'])), models.Q(('destino__isnull', True), ('origem__isnull', False), ('tipo', 'SAIDA')), models.Q(('destino__isnull', False), ('origem__isnull', False), ('tipo', 'TRANSFERENCIA')), ('tipo', 'AJUSTE'), _connector='OR'), name='movimentacao_origem_destino_coerentes'),
        ),
        migrations.AddConstraint(
            model_name='movimentacao',
            constraint=models.CheckConstraint(condition=models.Q(('origem', models.F('destino')), ('tipo', 'TRANSFERENCIA'), _negated=True), name='transferencia_origem_diferente_destino'),
        ),
    ]
