# Generated by Django 6.0.7 on 2026-07-21 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True)),
                ('descricao', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'feriado',
                'verbose_name_plural': 'feriados',
                'ordering': ['data'],
            },
        ),
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('sigla', models.CharField(max_length=10, unique=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'filial',
                'verbose_name_plural': 'filiais',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='MotivoRequisicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'motivo de requisição',
                'verbose_name_plural': 'motivos de requisição',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='CentroCusto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='centros_custo', to='cadastros.filial')),
            ],
            options={
                'verbose_name': 'centro de custo',
                'verbose_name_plural': 'centros de custo',
                'ordering': ['filial', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=200)),
                ('nome_fantasia', models.CharField(blank=True, max_length=200)),
                ('cnpj', models.CharField(blank=True, max_length=18)),
                ('contato', models.CharField(blank=True, max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('condicoes_pagamento', models.CharField(blank=True, max_length=200)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'fornecedor',
                'verbose_name_plural': 'fornecedores',
                'ordering': ['razao_social'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('cnpj', ''), _negated=True), fields=('cnpj',), name='cnpj_unico_quando_informado')],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('especificacao', models.CharField(help_text='Cor, gramatura, tamanho, marca de referência etc.', max_length=300)),
                ('grupo', models.CharField(choices=[('MATERIAL', 'Material'), ('SERVICO', 'Serviço')], default='MATERIAL', max_length=20)),
                ('tipo', models.CharField(blank=True, max_length=100)),
                ('unidade_medida', models.CharField(choices=[('UN', 'Unidade'), ('CX', 'Caixa'), ('PC', 'Pacote'), ('RM', 'Resma'), ('KG', 'Quilograma'), ('G', 'Grama'), ('L', 'Litro'), ('ML', 'Mililitro'), ('M', 'Metro'), ('RL', 'Rolo'), ('PAR', 'Par'), ('KIT', 'Kit')], default='UN', max_length=5)),
                ('reutilizavel', models.BooleanField(default=False, help_text='Exige devolução ao término do projeto')),
                ('ativo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='cadastros.categoria')),
                ('fornecedor_padrao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos_padrao', to='cadastros.fornecedor')),
            ],
            options={
                'verbose_name': 'produto',
                'verbose_name_plural': 'produtos',
                'ordering': ['nome', 'especificacao'],
            },
        ),
        migrations.CreateModel(
            name='Subcentro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('centro_custo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcentros', to='cadastros.centrocusto')),
            ],
            options={
                'verbose_name': 'subcentro',
                'verbose_name_plural': 'subcentros',
                'ordering': ['centro_custo', 'nome'],
            },
        ),
        migrations.AddConstraint(
            model_name='centrocusto',
            constraint=models.UniqueConstraint(fields=('filial', 'nome'), name='centro_unico_por_filial'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['categoria', 'ativo'], name='cadastros_p_categor_ce0e3b_idx'),
        ),
        migrations.AddConstraint(
            model_name='produto',
            constraint=models.UniqueConstraint(fields=('nome', 'especificacao'), name='produto_unico_por_especificacao'),
        ),
        migrations.AddConstraint(
            model_name='subcentro',
            constraint=models.UniqueConstraint(fields=('centro_custo', 'nome'), name='subcentro_unico_por_centro'),
        ),
    ]
