# Generated by Django 6.0.7 on 2026-07-21 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_seed_dados_iniciais'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='codigo',
            field=models.CharField(blank=True, help_text='Código interno importado (chave de reimportação)', max_length=30, null=True, unique=True),
        ),
    ]
