# Generated by Django 5.0.14 on 2026-09-28 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=200)),
                ('nome_fantasia', models.CharField(max_length=200)),
                ('cnpj', models.CharField(max_length=14)),
                ('codigo_prodados', models.CharField(blank=True, max_length=50)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'cnpj')},
            },
        ),
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('codigo_prodados', models.CharField(blank=True, max_length=50)),
                ('ativo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='filiais', to='tenancy.empresa')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CentroCusto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('codigo_prodados', models.CharField(blank=True, max_length=50)),
                ('ativo', models.BooleanField(default=True)),
                ('centro_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcentros', to='tenancy.centrocusto')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tenant')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='centros_custo', to='tenancy.filial')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Almoxarifado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('eh_central', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tenant')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='almoxarifados', to='tenancy.filial')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MotivoRequisicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('ativo', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
