# Generated by Django 6.0.7 on 2026-07-21 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0003_produto_codigo'),
        ('estoque', '0002_debitoalmoxarifado_movimentacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('ENVIADO', 'Aguardando aprovação'), ('APROVADO_UNIDADE', 'Aprovado — aguardando suprimentos'), ('RECUSADO', 'Recusado'), ('EM_SEPARACAO', 'Em separação'), ('ENTREGUE', 'Entregue'), ('CONCLUIDO', 'Concluído')], default='RASCUNHO', max_length=20)),
                ('observacao', models.CharField(blank=True, max_length=500)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('almoxarifado_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='estoque.almoxarifado')),
                ('centro_custo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='cadastros.centrocusto')),
                ('motivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='cadastros.motivorequisicao')),
                ('requisitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to=settings.AUTH_USER_MODEL)),
                ('subcentro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='cadastros.subcentro')),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=12)),
                ('origem_atendimento', models.CharField(blank=True, choices=[('ESTOQUE', 'Estoque'), ('COMPRA', 'Compra')], max_length=10, null=True)),
                ('quantidade_entregue', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('observacao', models.CharField(blank=True, max_length=300)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_pedido', to='cadastros.produto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='pedidos.pedido')),
            ],
            options={
                'verbose_name': 'item do pedido',
                'verbose_name_plural': 'itens do pedido',
            },
        ),
        migrations.CreateModel(
            name='EventoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('de_status', models.CharField(blank=True, choices=[('RASCUNHO', 'Rascunho'), ('ENVIADO', 'Aguardando aprovação'), ('APROVADO_UNIDADE', 'Aprovado — aguardando suprimentos'), ('RECUSADO', 'Recusado'), ('EM_SEPARACAO', 'Em separação'), ('ENTREGUE', 'Entregue'), ('CONCLUIDO', 'Concluído')], max_length=20)),
                ('para_status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('ENVIADO', 'Aguardando aprovação'), ('APROVADO_UNIDADE', 'Aprovado — aguardando suprimentos'), ('RECUSADO', 'Recusado'), ('EM_SEPARACAO', 'Em separação'), ('ENTREGUE', 'Entregue'), ('CONCLUIDO', 'Concluído')], max_length=20)),
                ('observacao', models.CharField(blank=True, max_length=500)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos_pedido', to=settings.AUTH_USER_MODEL)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='pedidos.pedido')),
            ],
            options={
                'verbose_name': 'evento do pedido',
                'verbose_name_plural': 'eventos do pedido',
                'ordering': ['criado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['status', 'ativo'], name='pedidos_ped_status_b7ba29_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['requisitante', 'status'], name='pedidos_ped_requisi_30541c_idx'),
        ),
        migrations.AddConstraint(
            model_name='itempedido',
            constraint=models.UniqueConstraint(fields=('pedido', 'produto'), name='produto_unico_por_pedido'),
        ),
        migrations.AddConstraint(
            model_name='itempedido',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade__gt', 0)), name='item_quantidade_positiva'),
        ),
    ]
