# Generated by Django 6.0.7 on 2026-09-30 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AprovacaoLider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aprovado_em', models.DateTimeField(auto_now_add=True)),
                ('lider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aprovacoes_como_lider', to=settings.AUTH_USER_MODEL)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aprovacoes_lider', to='pedidos.pedido')),
            ],
            options={
                'verbose_name': 'aprovação de líder',
                'verbose_name_plural': 'aprovações de líder',
                'ordering': ['aprovado_em'],
                'constraints': [models.UniqueConstraint(fields=('pedido', 'lider'), name='aprovacao_lider_unica_por_pedido')],
            },
        ),
    ]
