# Generated by Django 6.0.7 on 2026-09-29 19:50

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nome_completo', models.CharField(blank=True, max_length=150)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('ativo_no_sistema', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='tenancy.tenant')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuário',
                'verbose_name_plural': 'usuários',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Alcada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_min', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_max', models.DecimalField(blank=True, decimal_places=2, help_text='Vazio = sem teto (faixa mais alta)', max_digits=12, null=True)),
                ('papel_aprovador', models.CharField(choices=[('AUTOMATICA', 'Aprovação automática'), ('DIRETORIA_UNIDADE', 'Diretoria de Unidade'), ('CFO', 'CFO'), ('CEO', 'CEO')], max_length=30)),
                ('ativo', models.BooleanField(default=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'alçada de aprovação',
                'verbose_name_plural': 'alçadas de aprovação',
                'ordering': ['valor_min'],
                'constraints': [models.CheckConstraint(condition=models.Q(('valor_max__isnull', True), ('valor_max__gt', models.F('valor_min')), _connector='OR'), name='valor_max_maior_que_min')],
            },
        ),
        migrations.CreateModel(
            name='PapelUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('SUPERADMIN', 'SuperAdmin'), ('ADMINISTRADOR', 'Administrador'), ('APROVADOR', 'Aprovador'), ('SOLICITANTE', 'Solicitante')], max_length=20)),
                ('modulo', models.CharField(blank=True, choices=[('ESTOQUE', 'Estoque'), ('COMPRAS', 'Compras'), ('FINANCEIRO', 'Financeiro')], max_length=20, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papeis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'papel do usuário',
                'verbose_name_plural': 'papéis dos usuários',
                'constraints': [models.UniqueConstraint(fields=('usuario', 'papel', 'modulo'), name='papel_unico_por_usuario_modulo', nulls_distinct=False), models.CheckConstraint(condition=models.Q(models.Q(('modulo__isnull', False), ('papel', 'ADMINISTRADOR')), models.Q(('papel', 'ADMINISTRADOR'), _negated=True), _connector='OR'), name='administrador_exige_modulo')],
            },
        ),
        migrations.CreateModel(
            name='VinculoAprovacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveSmallIntegerField(default=1, help_text='Sequência quando há mais de um aprovador')),
                ('ativo', models.BooleanField(default=True)),
                ('aprovador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_como_aprovador', to=settings.AUTH_USER_MODEL)),
                ('requisitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_como_requisitante', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'vínculo de aprovação',
                'verbose_name_plural': 'vínculos de aprovação',
                'ordering': ['requisitante', 'ordem'],
                'constraints': [models.UniqueConstraint(fields=('requisitante', 'aprovador'), name='vinculo_unico'), models.UniqueConstraint(condition=models.Q(('ativo', True)), fields=('requisitante', 'ordem'), name='ordem_unica_por_requisitante_ativo'), models.CheckConstraint(condition=models.Q(('requisitante', models.F('aprovador')), _negated=True), name='aprovador_diferente_do_requisitante')],
            },
        ),
    ]
