# Generated by Django 6.0.7 on 2026-07-21 01:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alcada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_min', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_max', models.DecimalField(blank=True, decimal_places=2, help_text='Vazio = sem teto (faixa mais alta)', max_digits=12, null=True)),
                ('papel_aprovador', models.CharField(choices=[('AUTOMATICA', 'Aprovação automática'), ('DIRETORIA_UNIDADE', 'Diretoria de Unidade'), ('CFO', 'CFO'), ('CEO', 'CEO')], max_length=30)),
                ('ativo', models.BooleanField(default=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'alçada de aprovação',
                'verbose_name_plural': 'alçadas de aprovação',
                'ordering': ['valor_min'],
                'constraints': [models.CheckConstraint(condition=models.Q(('valor_max__isnull', True), ('valor_max__gt', models.F('valor_min')), _connector='OR'), name='valor_max_maior_que_min')],
            },
        ),
        migrations.CreateModel(
            name='VinculoAprovacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveSmallIntegerField(default=1, help_text='Sequência quando há mais de um aprovador')),
                ('ativo', models.BooleanField(default=True)),
                ('aprovador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_como_aprovador', to=settings.AUTH_USER_MODEL)),
                ('requisitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_como_requisitante', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'vínculo de aprovação',
                'verbose_name_plural': 'vínculos de aprovação',
                'ordering': ['requisitante', 'ordem'],
                'constraints': [models.UniqueConstraint(fields=('requisitante', 'aprovador'), name='vinculo_unico'), models.UniqueConstraint(condition=models.Q(('ativo', True)), fields=('requisitante', 'ordem'), name='ordem_unica_por_requisitante_ativo'), models.CheckConstraint(condition=models.Q(('requisitante', models.F('aprovador')), _negated=True), name='aprovador_diferente_do_requisitante')],
            },
        ),
    ]
