# Generated by Django 6.0.7 on 2026-09-30 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_seed_alcadas'),
        ('tenancy', '0002_seed_dados_iniciais'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cargo',
            field=models.CharField(blank=True, help_text='Cargo/função, ex.: Coordenadora Pedagógica', max_length=100),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ciclo',
            field=models.CharField(blank=True, choices=[('EDUCACAO_INFANTIL', 'Educação Infantil'), ('ANOS_INICIAIS', 'Anos Iniciais'), ('ANOS_FINAIS', 'Anos Finais'), ('ENSINO_MEDIO', 'Ensino Médio'), ('ADMINISTRATIVO', 'Administrativo')], max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='tenancy.filial'),
        ),
    ]
