# Generated by Django 6.0.7 on 2026-09-30 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0003_usuario_cargo_usuario_ciclo_usuario_filial'),
        ('tenancy', '0002_seed_dados_iniciais'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegraAprovacaoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modo_aprovacao_setor', models.CharField(choices=[('QUALQUER_LIDER', 'Qualquer líder do setor aprova'), ('TODOS_LIDERES', 'Todos os líderes do setor devem aprovar')], default='QUALQUER_LIDER', max_length=20)),
            ],
            options={
                'verbose_name': 'regra de aprovação',
                'verbose_name_plural': 'regras de aprovação',
            },
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'setor',
                'verbose_name_plural': 'setores',
                'ordering': ['filial', 'nome'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='vinculoaprovacao',
            name='vinculo_unico',
        ),
        migrations.RemoveConstraint(
            model_name='vinculoaprovacao',
            name='ordem_unica_por_requisitante_ativo',
        ),
        migrations.RemoveConstraint(
            model_name='vinculoaprovacao',
            name='aprovador_diferente_do_requisitante',
        ),
        migrations.AddField(
            model_name='regraaprovacaoempresa',
            name='empresa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='regra_aprovacao', to='tenancy.empresa'),
        ),
        migrations.AddField(
            model_name='setor',
            name='filial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='setores', to='tenancy.filial'),
        ),
        migrations.AddField(
            model_name='setor',
            name='lideres',
            field=models.ManyToManyField(blank=True, related_name='setores_liderados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='setor',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='membros', to='contas.setor'),
        ),
        migrations.RemoveField(
            model_name='vinculoaprovacao',
            name='aprovador',
        ),
        migrations.RemoveField(
            model_name='vinculoaprovacao',
            name='requisitante',
        ),
        migrations.AddConstraint(
            model_name='setor',
            constraint=models.UniqueConstraint(fields=('filial', 'nome'), name='setor_unico_por_filial'),
        ),
        migrations.DeleteModel(
            name='VinculoAprovacao',
        ),
    ]
