# Generated by Django 5.0.14 on 2026-09-28 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemKitRequisicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_sugerida', models.DecimalField(decimal_places=3, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='KitRequisicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_interno', models.CharField(max_length=30, unique=True)),
                ('nome', models.CharField(max_length=200)),
                ('especificacao', models.TextField(help_text="Obrigatório. Cor, gramatura etc. — elimina o 'pedido vago'. O requisitante escolhe o item já especificado, nunca digita livre no pedido (exceto via ItemLivreRequisicao, fora do escopo da Fase 0).")),
                ('unidade_base', models.CharField(max_length=10)),
                ('fator_embalagem_compra', models.PositiveIntegerField(default=1)),
                ('unidade_embalagem_compra', models.CharField(blank=True, max_length=10)),
                ('reutilizavel', models.BooleanField(default=False, help_text='Flag informativa apenas. Controle de devolução está fora do MVP (ver docs/06-Glossario-e-Fora-de-Escopo.html) — não bloqueia conclusão de pedido.')),
                ('categoria_investimento', models.BooleanField(default=False, help_text='Bens duráveis (notebook, mobiliário). Separa relatório de consumo de gasto operacional. Sem controle patrimonial no MVP.')),
                ('estoque_minimo', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('ponto_reposicao', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('ativo', models.BooleanField(default=True)),
                ('aprovado_por_suprimentos', models.BooleanField(default=True, help_text='False apenas para produtos criados a partir de ItemLivreRequisicao ainda não confirmados por suprimentos. Produto assim não pode ser movimentado em estoque nem comprado.')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CategoriaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('categoria_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcategorias', to='cadastros.categoriaproduto')),
            ],
            options={
                'verbose_name_plural': 'categorias de produto',
            },
        ),
    ]
