# Generated by Django 5.0.14 on 2026-09-28 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
        ('compras', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaproduto',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tenant'),
        ),
        migrations.AddField(
            model_name='kitrequisicao',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tenant'),
        ),
        migrations.AddField(
            model_name='itemkitrequisicao',
            name='kit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='cadastros.kitrequisicao'),
        ),
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='cadastros.categoriaproduto'),
        ),
        migrations.AddField(
            model_name='produto',
            name='fornecedor_padrao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos_padrao', to='compras.fornecedor'),
        ),
        migrations.AddField(
            model_name='produto',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tenant'),
        ),
        migrations.AddField(
            model_name='itemkitrequisicao',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.produto'),
        ),
        migrations.AlterUniqueTogether(
            name='itemkitrequisicao',
            unique_together={('kit', 'produto')},
        ),
    ]
